// Mur d'actualité — entrées affichées sur /nouveautes (la plus récente en premier).
// tag : 'Nouveauté' | 'Amélioration' | 'Correctif'

export const NEWS = [
  {
    date: "2026-10-06",
    version: "3.14.2",
    tag: "Correctif",
    title: "Un paiement ZIK Pro plus clair",
    items: [
      "Avant de payer, un récapitulatif confirme la formule, le prix, le compte et la date de fin de l'accès.",
      "Si un passe Soirée est déjà actif, ZIK le signale avant le paiement : un nouveau passe ajoute 24 h à la suite, pour éviter de payer deux fois par erreur.",
      "Après le paiement, la page de confirmation affiche la formule et la date exacte de fin de l'accès.",
      "La page ZIK Pro se met à jour quand on y revient, et rappelle en haut de page que l'accès est actif.",
    ],
  },
  {
    date: "2026-10-04",
    version: "3.14.1",
    tag: "Correctif",
    title: "Les images de partage retrouvent la police de ZIK",
    items: [
      "Les images générées pour partager un résultat de partie s'affichaient avec une police de remplacement au lieu de celle du site. Elles utilisent de nouveau Barlow, comme partout sur ZIK.",
    ],
  },
  {
    date: "2026-10-03",
    version: "3.14.0",
    tag: "Amélioration",
    title: "La régie se pilote depuis un téléphone",
    items: [
      "La régie du Mode Salon s'utilise maintenant aussi bien sur téléphone et tablette que sur un second écran : le minuteur, les joueurs et les boutons Pause et Révéler restent à portée sans avoir à faire défiler la page.",
      "Elle prévient quand aucun écran TV n'est connecté - la musique ne jouerait pas - et quand deux le sont, auquel cas le son joue en double.",
      "Les points d'un joueur se corrigent en tapant directement le chiffre, en plus des boutons plus et moins.",
      "Changer le nombre d'équipes ne réinitialise plus les noms que vous avez saisis, et ne déplace plus personne d'une équipe à l'autre.",
      "Les joueurs ne sont plus rangés d'office dans une équipe : chacun choisit la sienne sur son téléphone, ou vous la lui donnez depuis la régie.",
      "« Terminer la partie » demande une confirmation : plus de soirée coupée par un geste de travers.",
      "Sur la page de préparation, ce que ZIK Pro débloque est enfin visible, et les options qui le nécessitent sont clairement signalées.",
    ],
  },
  {
    date: "2026-10-03",
    version: "3.13.0",
    tag: "Amélioration",
    title: "Le site s'adapte vraiment au mobile",
    items: [
      "Le thème se change depuis la barre du haut, sans compte et sans passer par les paramètres.",
      "Sur mobile, la barre du bas ne masque plus la fin des pages, y compris sur les iPhone à encoche.",
      "Le menu du profil ne répète plus les liens déjà présents dans la barre du bas, et donne accès à l'aide et au soutien.",
      "Page de profil allégée : votre rang s'affiche avec son classement complet, les répétitions ont disparu et les sections vides ne s'affichent plus.",
      "En thème clair, la page des rooms ne mélange plus les couleurs.",
      "Les pages de comparaison affichaient leur titre sous le menu : corrigé, et leur tableau se lit enfin sur téléphone.",
      "Plusieurs pages gagnent un fil d'Ariane et des informations manquantes pour les moteurs de recherche.",
    ],
  },
  {
    date: "2026-10-02",
    version: "3.12.0",
    tag: "Amélioration",
    title: "ZIK passe au thème clair",
    items: [
      "Le site s'affiche désormais en thème clair par défaut, aux couleurs de ZIK. Le thème sombre reste disponible dans les paramètres.",
      "Page d'accueil plus claire : une action principale pour organiser une soirée, un menu plus lisible et des textes plus contrastés.",
      "Nouveau bloc « Aujourd'hui sur ZIK » sur l'accueil : ton Zikle du jour et ta série, le défi de la semaine, et ta dernière room à reprendre en un clic.",
      "Accueil allégé : moins de blocs, et l'essentiel en premier.",
      "Le code d'une soirée (affiché sur la TV) et le code d'une partie en ligne ne se confondent plus.",
      "Depuis la page des rooms, les invités choisissent maintenant leur pseudo au lieu de tous s'appeler « Joueur ».",
      "L'écran TV du Mode Salon reste sombre pour ne pas éblouir la pièce.",
      "Zikle explique ses règles dès la première visite, et la page d'erreur propose de quoi rebondir.",
      "Navigation au clavier visible partout, zoom autorisé sur mobile, et respect du réglage « réduire les animations ».",
      "En partie, le compte à rebours au centre du vinyle redevient lisible, et les invités savent qu'un compte gratuit garde leur score.",
    ],
  },
  {
    date: "2026-09-30",
    version: "3.10.0",
    tag: "Nouveauté",
    title: "ZIK Pro s'achète en ligne",
    items: [
      "Les bars, campings et organisateurs d'événements peuvent prendre ZIK Pro directement sur le site : passe Soirée à 7,90 €, abonnement mensuel à 19 € ou annuel à 190 €.",
      "Paiement sécurisé par Stripe (carte, Apple Pay, Google Pay), facture envoyée automatiquement, ZIK Pro activé dans la seconde.",
      "Abonnement sans engagement : factures, carte bancaire et résiliation se gèrent en un clic depuis la page Mode Salon ou les paramètres.",
      "Nouvelles conditions générales de vente, et mentions légales mises à jour.",
    ],
  },
  {
    date: "2026-09-29",
    version: "3.9.1",
    tag: "Amélioration",
    title: "Un mail de confirmation pour ZIK Pro",
    items: [
      "Les lieux qui s'inscrivent sur la liste d'attente ZIK Pro reçoivent un e-mail de confirmation, avec les formules et de quoi essayer le Mode Salon tout de suite.",
      "Les e-mails de ZIK (inscription, mot de passe oublié) adoptent les couleurs du site.",
    ],
  },
  {
    date: "2026-09-29",
    version: "3.9.0",
    tag: "Nouveauté",
    title: "Le Mode Salon passe en version soirée",
    items: [
      "Nouvel écran TV, plus lisible depuis le canapé : un grand chrono, la réponse en bandeau, un classement qui bouge en direct et un vrai podium en fin de partie.",
      "Joue en équipes : l'hôte choisit le nombre d'équipes, chacun rejoint la sienne depuis son téléphone. Le score d'une équipe est la moyenne de ses joueurs, pour que les petites tables aient leur chance.",
      "La régie : ouvre-la sur un second écran pour piloter la soirée (pause, manche suivante, réglages) pendant que la TV montre le jeu.",
      "Sur téléphone, les quatre réponses prennent tout l'écran, et le classement s'anime quand la bonne réponse tombe.",
      "Plus sûr : l'écran TV et la régie sont réservés à l'hôte, personne ne peut prendre le pseudo d'un autre joueur, et un joueur exclu ne revient pas.",
      "Pour les bars, campings et événements, ZIK Pro arrive : joueurs illimités, jusqu'à 8 équipes et la régie complète. Le salon reste gratuit jusqu'à 12 joueurs.",
      "La musique se charge pendant la manche en cours : sur une connexion lente, la suivante démarre sans attendre.",
      "Fini les manches muettes : les extraits de secours étaient souvent périmés au moment de jouer, surtout sur la première manche. Ils sont maintenant préparés juste avant chaque manche et renouvelés s'ils expirent en cours de lecture.",
      "Plus besoin de compte pour organiser une soirée en Mode Salon : choisis une playlist publique ou officielle et lance. Avec un compte, tu gardes l'accès à tes propres playlists.",
      "Un invité qui arrive en retard peut rejoindre un salon déjà lancé : il entre dans la manche en cours avec 0 point.",
      "Nouvelles pages Blind test par thème (années 80, rap français, Disney…) et par occasion (soirée entre amis, bar, camping, team building, anniversaire, mariage), avec un bouton pour lancer directement la playlist en soirée.",
      "Seul dans une room ? Un bouton copie le lien pour inviter tes amis, un autre t'emmène vers le Mode Salon.",
    ],
  },
  {
    date: "2026-09-09",
    version: "3.8.2",
    tag: "Correctif",
    title: "Les parties coupées par la modération comptent",
    items: [
      "Quand une partie était interrompue depuis l'interface d'administration, les points marqués n'étaient enregistrés nulle part : ni au classement, ni dans les statistiques du profil. Ils comptent maintenant, comme pour une partie arrivée à son terme.",
    ],
  },
  {
    date: "2026-09-09",
    version: "3.8.1",
    tag: "Correctif",
    title: "Le classement Score comptait mal les parties",
    items: [
      "Les parties jouées dans une room créée à la volée n'apparaissaient nulle part dans le classement Score, alors qu'elles comptaient sur la page d'accueil. Des dizaines de joueurs étaient invisibles au classement : c'est réparé, et leurs points sont revenus.",
      "Quand une partie était abandonnée par tous ses joueurs, les points marqués avant de partir étaient bien enregistrés mais jamais classés. Ils comptent désormais.",
      "Un même compte pouvait jouer depuis deux onglets à la fois et voir ses points comptés en double. Ce n'est plus possible : tant qu'une partie est ouverte quelque part, le second onglet propose de reprendre la main plutôt que de créer un deuxième joueur.",
    ],
  },
  {
    date: "2026-09-09",
    version: "3.8.0",
    tag: "Nouveauté",
    title: "Ton score s'affiche enfin quand tu partages une partie",
    items: [
      "Quand tu partages le lien d'une partie terminée, l'aperçu sur WhatsApp, Discord ou les réseaux montre maintenant une vraie carte de score : ton pseudo, tes points, ton rang et le thème de la room. Avant, c'était la même image passe-partout pour tout le monde.",
      "Nouvelle page Organiser une soirée, pensée pour les bars, les associations et les comités d'entreprise qui veulent monter un blind test sur grand écran. Le Mode Salon reste gratuit et sans limite, elle explique juste comment s'y prendre.",
      "Un cookie de mesure a été ajouté pour savoir combien de personnes arrivent sur le site et d'où elles viennent. Il ne contient aucun identifiant, ne permet pas de te reconnaître, et rien n'est transmis à un service extérieur. La politique de confidentialité le détaille.",
    ],
  },
  {
    date: "2026-09-08",
    version: "3.7.1",
    tag: "Amélioration",
    title: "Nouvelles icônes et nouvelle image de partage",
    items: [
      "Le carré du logo passe du violet au magenta du site. L'icône reste la même, mais elle est enfin de la bonne couleur dans l'onglet, sur l'écran d'accueil du téléphone et dans les favoris.",
      "L'image affichée quand on partage un lien ZIK sur Discord, WhatsApp ou les réseaux a été entièrement refaite : la punchline de la page d'accueil sur un mur de pochettes, et surtout la bonne adresse du site. L'ancienne datait des débuts et affichait encore un nom de domaine qui n'existe plus.",
    ],
  },
  {
    date: "2026-09-08",
    version: "3.7.0",
    tag: "Nouveauté",
    title: "Une page pour soutenir le projet",
    items: [
      "ZIK tourne sur un serveur payé de ma poche, entre 5 et 15 € par mois selon l'affluence. La page Soutenir explique où va l'argent et permet de participer aux frais si le cœur t'en dit.",
      "Rien ne change dans le jeu : les dons sont libres et ne donnent accès à aucun avantage, aucun bonus et aucun contenu réservé. Tout le monde garde exactement le même ZIK.",
      "La publicité disparaît complètement du site : plus aucun encart, plus aucun script publicitaire, plus aucun cookie de ce type. La politique de confidentialité a été mise à jour en conséquence.",
      "La fenêtre d'informations qui s'ouvrait à l'arrivée sur le site est supprimée, ainsi que le réglage qui servait à la masquer.",
      "Zikle : la lecture est maintenant strictement limitée à la durée débloquée, quelle que soit la façon dont elle est lancée. Il restait possible d'entendre l'extrait complet en contournant le bouton Écouter.",
    ],
  },
  {
    date: "2026-08-27",
    version: "3.6.1",
    tag: "Correctif",
    title: "Zikle : passer un tour coupe enfin l'extrait",
    items: [
      "Quand tu passais un tour ou te trompais pendant la lecture, l'extrait continuait jusqu'au bout du morceau. Il s'arrête maintenant net : il faut réappuyer sur Écouter pour entendre la nouvelle durée débloquée.",
    ],
  },
  {
    date: "2026-08-26",
    version: "3.6.0",
    tag: "Amélioration",
    title: "Signaler un titre muet, et une fin de partie plus posée",
    items: [
      "Quand tu n'entends pas la musique, le signalement te laisse désigner le ou les titres concernés, y compris celui de la manche en cours — sans en dévoiler la réponse.",
      "Les autres bugs se signalent toujours librement, avec un motif pour les orienter plus vite.",
      "Les signalements envoyés sans être connecté n'arrivaient jamais : ils partaient en erreur au moment de l'envoi. C'est corrigé.",
      "Fin de partie : un décompte de 15 secondes lance la partie suivante. Tu peux relancer tout de suite, ou laisser filer le décompte en regardant les scores.",
      "Quand quelqu'un d'autre relance, tu n'es plus arraché au tableau des scores en pleine lecture : tu le rejoins à la fin du décompte.",
      "L'écran de fin est réorganisé : l'action du moment d'abord, le partage et la navigation en dessous, à taille égale.",
    ],
  },
  {
    date: "2026-08-25",
    version: "3.5.0",
    tag: "Amélioration",
    title: "Les pages de room racontent enfin quelque chose",
    items: [
      "Chaque room affiche ses règles selon son mode de jeu, son nombre de manches et la durée d'une manche : une room Classique et sa variante Casual ne se ressemblent plus.",
      "Les artistes les plus présents dans la playlist sont listés, avec leur nombre de titres — sans jamais dévoiler les morceaux, qui restent la réponse du blind test.",
      "Le classement de la semaine de la room est visible directement sur sa page.",
      "Les pages sans contenu propre sortent de l'index Google, ce qui concentre le référencement sur les pages qui en valent la peine.",
      "Sur mobile, le panneau du défi hebdomadaire ne déborde plus de l'écran une fois déplié.",
    ],
  },
  {
    date: "2026-08-13",
    version: "3.4.0",
    tag: "Nouveauté",
    title: "Défi communautaire hebdomadaire",
    items: [
      "Chaque semaine, un objectif collectif est proposé à toute la communauté : bonnes réponses, parties jouées ou victoires Zikle cumulées par tous les joueurs.",
      "Si l'objectif est atteint avant la fin de la semaine, tous les participants débloquent un succès collectif.",
      "Le joueur ayant le plus contribué devient le top contributeur de la semaine et débloque un succès dédié, affiché avec un ×N sur le profil s'il est obtenu plusieurs semaines différentes.",
      "Le défi en cours, sa progression et le top 3 des contributeurs sont affichés sur la page d'accueil.",
      "Nouvelle page /defi : classement complet de la semaine en cours et historique de tous les défis passés, avec le classement détaillé de chaque semaine.",
      "La page d'accueil présente aussi désormais toutes les fonctionnalités du site (Zikle, Mode Salon, QCM, succès, social) et un aperçu des dernières nouveautés.",
    ],
  },
  {
    date: "2026-08-11",
    version: "3.3.2",
    tag: "Correctif",
    title: "Mobile — les réponses QCM sont enfin lisibles en entier",
    items: [
      "Mode Salon : le libellé des boutons de réponse était coupé par des points de suspension sur téléphone. Il passe désormais à la ligne, artiste et titre restent lisibles en entier — indispensable quand deux propositions partagent le même artiste.",
      "Blind test en QCM : sur mobile, les quatre réponses s'affichent sur une seule colonne pleine largeur au lieu de deux colonnes trop étroites.",
      "L'historique des titres joués affiche l'artiste et le titre complets sur mobile, sans troncature.",
    ],
  },
  {
    date: "2026-08-11",
    version: "3.3.1",
    tag: "Correctif",
    title: "Zikle — les versions d'un même titre ne piègent plus",
    items: [
      "Proposer « Smooth Criminal - Radio Edit » quand la réponse est « Smooth Criminal » compte désormais comme trouvé : radio edits, remasters, versions live et featurings sont reconnus comme le même morceau.",
      "Les suggestions de recherche fusionnent ces variantes : un morceau n'apparaît plus qu'une fois dans la liste, sous son titre le plus simple.",
      "Le classement du jour affiche aussi les joueurs qui n'ont pas trouvé, dans une section « Ont tenté » séparée du podium : on voit tous ceux qui ont tenté leur chance sans confondre les deux.",
      "Classement dépliable avec un bouton « Voir plus », et ton rang réel est toujours rappelé sous la liste, même si tu n'es pas dans les premiers.",
    ],
  },
  {
    date: "2026-08-05",
    version: "3.2.0",
    tag: "Nouveauté",
    title: "Zikle — la chanson du jour",
    items: [
      "Nouveau jeu quotidien solo : une seule chanson par jour, la même pour tout le monde, à deviner en 6 essais. L'extrait démarre à 1 seconde et s'allonge à chaque erreur (1s, 2s, 4s, 7s, 11s, 16s).",
      "Jouable sans compte : le Zikle du jour est accessible librement, comme le reste du site en mode invité.",
      "Les titres sont tirés du top Deezer, rafraîchi chaque semaine — que des morceaux qui ont marché, et jamais deux fois le même titre avant 365 jours.",
      "Chaque essai indique clairement son état : trouvé, raté (avec la proposition faite) ou passé.",
      "Réglage du volume directement sous le lecteur, mémorisé d'une partie à l'autre.",
      "Série de jours gagnés d'affilée, classement du jour pour les joueurs connectés, et partage d'une grille d'emojis sans spoiler.",
      "Archives : rejoue les journées passées avec un compte gratuit. Les jours déjà terminés y affichent ton score.",
      "Zikle est accessible depuis la navigation du site, en haut sur ordinateur et dans la barre du bas sur mobile.",
    ],
  },
  {
    date: "2026-07-11",
    version: "3.0.0",
    tag: "Nouveauté",
    title: "ZIK v3 — Nouvelle interface",
    items: [
      "Refonte graphique complète du site : accueil, rooms, classements, playlists, profil, connexion, documentation et Mode Salon (nouvelle ambiance scène de festival côté hôte).",
      "Amis et abonnements : suis un profil librement ou envoie une demande d'ami (confirmée des deux côtés). Les demandes reçues s'acceptent depuis ton profil ou tes notifications.",
      "Ajoute un joueur en ami directement pendant une partie (menu ⋯ du classement) et invite tes amis dans ta room en un clic (bouton 👋 en haut de l'écran de jeu).",
      "Page d'accueil : les rooms avec des joueurs en ligne sont mises en avant dans une section « En direct », et des onglets Classique / QCM permettent de choisir son mode.",
      "La synchronisation de la musique entre joueurs a été renforcée : reprise au bon endroit après reconnexion et recalage automatique en cas de dérive.",
      "Mode Salon : barre de volume directement dans l'en-tête de l'écran hôte, et boutons de retour vers l'accueil sur toutes les pages Salon.",
      "Mot de passe oublié : un lien sur la fenêtre de connexion permet de recevoir un email de réinitialisation.",
      "En jeu sur mobile : le chrono du disque est plus lisible et n'apparaît plus avant le début de la partie.",
      "La fenêtre d'invitation d'un ami affiche les rooms en grille compacte, bien plus lisible sur PC comme sur mobile.",
      "Rooms améliorées : description en textarea, sélecteur de playlists retravaillé, et liaison Discord rafraîchie sans recharger la page.",
      "Divers correctifs : bouton Retour cliquable sur la Documentation, saisie du code room plus confortable sur mobile, page Profil hors connexion mieux espacée.",
      "Documentation enrichie (section Amis & invitations) et fichiers légaux mis à jour (fonctionnalités sociales, Bot Discord, publicité).",
    ],
  },
  {
    date: "2026-06-11",
    version: "2.7.0",
    tag: "Nouveauté",
    title: "Profil repensé : onglets, stats par mode et Early Adopter",
    items: [
      "Le profil est maintenant organisé en onglets : 📊 Statistiques et 🏅 Succès.",
      "Les statistiques séparent enfin le mode Classique et le mode QCM : plus de scores mélangés !",
      "Le succès 🌟 Early Adopter est attribué automatiquement à tous les comptes créés avant le 1er juin 2026. Merci les précurseurs !",
    ],
  },
  {
    date: "2026-06-10",
    version: "2.6.0",
    tag: "Nouveauté",
    title: "Succès, séries de jeu et scores partageables",
    items: [
      "Nouveau système de succès : 10 succès à débloquer (bronze, argent, or) visibles sur ton profil.",
      "Séries de jeu : enchaîne les jours de jeu et les victoires pour faire grimper tes records 🔥",
      "Partage ton score en fin de partie avec un lien public à envoyer à tes amis.",
      "Nouvelle page Nouveautés (celle que tu lis !) pour suivre les mises à jour du site.",
    ],
  },
  {
    date: "2026-06-04",
    version: "2.5.2",
    tag: "Correctif",
    title: "Playlists privées en Mode Salon",
    items: [
      "Les playlists privées ne sont plus proposées à la création d'un salon si elles ne t'appartiennent pas.",
      "Correction d'un crash rare côté serveur.",
    ],
  },
  {
    date: "2026-05-24",
    tag: "Correctif",
    title: "Sauvegarde des scores fiabilisée",
    items: [
      "Les points sont désormais sauvegardés manche par manche : plus de points perdus si tu quittes une partie en cours.",
      "Lecture audio réparée sur certaines musiques (recherche YouTube).",
      "Mises à jour de sécurité des dépendances.",
    ],
  },
  {
    date: "2026-05-14",
    version: "2.5.0",
    tag: "Nouveauté",
    title: "Page Classements & points en temps réel",
    items: [
      "Nouvelle page Classements : ELO, classement hebdomadaire et score total au même endroit.",
      "Les points gagnés sont ajoutés à ton profil en temps réel pendant la partie.",
      "Les previews audio Deezer se rafraîchissent automatiquement, même sans redémarrage du serveur.",
    ],
  },
  {
    date: "2026-05-06",
    tag: "Amélioration",
    title: "Refonte SEO du site",
    items: [
      "Pages repensées pour mieux présenter ZIK : accueil, documentation, comparatifs.",
      "Nouvelles pages de comparaison : ZIK vs Kahoot, ZIK vs Blinest, ZIK vs Blindtest.io.",
      "Meta descriptions dynamiques pour les rooms publiques.",
    ],
  },
  {
    date: "2026-04-26",
    version: "2.3.0",
    tag: "Correctif",
    title: "Audio : previews expirées réparées automatiquement",
    items: [
      "Les extraits musicaux dont le lien Deezer expirait deviennent silencieux : ils sont maintenant détectés et remplacés automatiquement.",
      "Filet de sécurité : si un extrait est indisponible, une source alternative est cherchée en direct.",
    ],
  },
  {
    date: "2026-04-25",
    tag: "Nouveauté",
    title: "Mode QCM multijoueur",
    items: [
      "Nouveau mode de jeu QCM dans les rooms multijoueur : 4 propositions, réponds le plus vite possible.",
      "Parfait pour découvrir le blind test sans connaître tous les titres par cœur.",
      "Chat en direct visible par les admins pour la modération.",
    ],
  },
  {
    date: "2026-04-14",
    tag: "Amélioration",
    title: "Refonte du profil et interface admin",
    items: [
      "Profil repensé : statistiques détaillées, historique de parties, profil public ou privé.",
      "Filtres et recherche améliorés sur la page Rooms.",
    ],
  },
  {
    date: "2026-04-03",
    tag: "Nouveauté",
    title: "Mode Salon : le blind test à la Kahoot",
    items: [
      "L'hôte diffuse la musique sur un grand écran, les joueurs répondent depuis leur téléphone via QR code.",
      "Mode texte libre ou QCM avec 4 boutons colorés.",
      "Idéal pour les soirées, anniversaires et événements.",
    ],
  },
];
