import { PH, cam, box, pt, C } from "./common.mjs";
const P = cam(PH, 1375);
export default {
  duration: 15.5,
  shots: [
    { a: 0, b: 3, rec: "qcm2", from: 4.2, cam: C(P) },
    { a: 3, b: 6.5, rec: "qcm2", from: 4.9, cam: C(P), slide: false },
    { a: 6.5, b: 10, rec: "qcm2", from: 20.4, cam: C(P) },
    { a: 10, b: 13.5, rec: "qcm2", from: 58.0, cam: C(P) },
  ],
  caps: [
    {
      a: 0.1,
      b: 3,
      y: 880,
      k: "Mode QCM",
      t: "Nul en blind test ?|*Pas grave.*",
    },
    {
      a: 3,
      b: 6.5,
      y: 880,
      k: "Étape 1",
      t: "Choisis parmi *4 réponses*",
      s: "Une seule est la bonne.",
    },
    {
      a: 6.5,
      b: 10,
      y: 880,
      k: "Étape 2",
      t: "*Plus tu es rapide*,|plus tu marques",
      s: "Le score dépend de ta vitesse.",
    },
    {
      a: 10,
      b: 13.5,
      y: 880,
      k: "La réponse",
      t: "La pochette *se dévoile*",
      s: "Tu découvres la chanson juste après.",
    },
  ],
  fx: [
    { type: "ring", a: 3.3, b: 4.0, ...box(P, 30, 1730, 1015, 460, 10) },
    {
      type: "count",
      a: 4.05,
      b: 6.5,
      ...pt(P, 540, 1150),
      size: 120,
      to: 951,
      prefix: "+",
      suffix: " pts",
    },
    { type: "confetti", a: 4.05, b: 5.5, ...pt(P, 540, 1000) },
    {
      type: "count",
      a: 8.75,
      b: 10,
      ...pt(P, 540, 1150),
      size: 120,
      to: 929,
      prefix: "+",
      suffix: " pts",
      r: 4,
    },
    {
      type: "ring",
      a: 11.2,
      b: 13.5,
      ...box(P, 200, 430, 670, 670, 6),
      rx: 340,
    },
  ],
  outro: { a: 13.5, l1: "Joue en *QCM*|seul ou à plusieurs" },
};
