const TV = (c = { t: 0, s: 1 }) => ({
  kind: "tv",
  rec: "salon3_tv",
  x: 40,
  y: 330,
  w: 1000,
  h: 563,
  cam: [c],
});
const ph = (rec, x) => ({
  kind: "phone",
  rec,
  x,
  y: 975,
  w: 400,
  h: 867,
  cam: [{ t: 0, s: 1 }],
});
const lay = (a, b, from, slide, c) => ({
  a,
  b,
  from,
  bg: "dark",
  slide,
  panels: [TV(c), ph("salon3_Julie", 110), ph("salon3_Karim", 570)],
});
const k = 1000 / 1920,
  tv = (x, y, w, h, p = 8) => ({
    x: 40 + x * k - p,
    y: 330 + y * k - p,
    w: w * k + 2 * p,
    h: h * k + 2 * p,
  });
export default {
  duration: 16.5,
  shots: [
    lay(0, 3.5, 1.0),
    lay(3.5, 7, 3.5, false),
    lay(7, 11, 25.4, false),
    lay(11, 14.5, 55.6, false, { t: 0, s: 2, x: 1440, y: 300 }),
  ],
  caps: [
    {
      a: 0.1,
      b: 3.5,
      y: 40,
      k: "Mode Salon",
      t: "Le blind test *de soirée*",
      s: "Ta TV + les téléphones de tes potes.",
    },
    {
      a: 3.5,
      b: 7,
      y: 40,
      k: "Étape 1",
      t: "Chacun rejoint *avec son tél*",
      s: "Un code, un pseudo. Sans appli.",
    },
    {
      a: 7,
      b: 11,
      y: 40,
      k: "Étape 2",
      t: "La musique passe *sur la TV*",
      s: "Et chacun répond sur son téléphone.",
    },
    {
      a: 11,
      b: 14.5,
      y: 40,
      k: "En équipes",
      t: "Rouge *contre* Bleue",
      s: "Le classement s’affiche en direct sur la TV.",
    },
  ],
  fx: [
    { type: "ring", a: 3.8, b: 7, ...tv(75, 495, 640, 130) },
    {
      type: "ring",
      a: 7.6,
      b: 9,
      x: 100,
      y: 965,
      w: 880,
      h: 887,
      color: "#ffe14d",
    },
    { type: "ring", a: 11.3, b: 14.5, x: 495, y: 390, w: 545, h: 495 },
    {
      type: "stamp",
      a: 12.75,
      b: 14.5,
      x: 540,
      y: 935,
      size: 84,
      text: "Rouge passe devant !",
      r: -4,
    },
  ],
  outro: { a: 14.5, l1: "Le blind test|de *soirée*" },
};
