import { PH, cam, box, C } from "./common.mjs";
const A = cam(PH, 1165),
  B = cam(PH, 1015),
  E = cam(PH, 1375);
export default {
  duration: 19.2,
  shots: [
    { a: 0, b: 3, rec: "zik2", from: 0.8, cam: C(A) },
    { a: 3, b: 6.2, rec: "zik2", from: 2.6, cam: C(A), slide: false },
    { a: 6.2, b: 9.7, rec: "zik2", from: 6.3, cam: C(B) },
    { a: 9.7, b: 14.2, rec: "zik2", from: 16.2, speed: 1.5, cam: C(B) },
    { a: 14.2, b: 17.2, rec: "zik2", from: 23.6, speed: 0.3, cam: C(E) },
  ],
  caps: [
    {
      a: 0.1,
      b: 3,
      y: 40,
      k: "Zikle",
      t: "*1 chanson* par jour",
      s: "Trouve-la en 6 essais maximum.",
    },
    {
      a: 3,
      b: 6.2,
      y: 40,
      k: "Étape 1",
      t: "Écoute et *propose un titre*",
      s: "Les suggestions t’aident à le retrouver.",
    },
    {
      a: 6.2,
      b: 9.7,
      y: 1430,
      k: "Raté ?",
      t: "Tu entends *un peu plus*",
      s: "Chaque essai raté débloque la suite de l’extrait.",
    },
    {
      a: 9.7,
      b: 12.75,
      y: 40,
      k: "Étape 2",
      t: "Retente *ta chance*",
      s: "Ou passe ton tour pour entendre la suite.",
    },
    {
      a: 12.75,
      b: 14.2,
      y: 40,
      k: "Bravo",
      t: "*Trouvé* en 3 essais !",
      s: "Stromae, Alors on danse.",
    },
    {
      a: 14.2,
      b: 17.2,
      y: 1500,
      k: "Classement du jour",
      t: "Compare-toi *à la commu*",
      s: "Tout le monde a la même chanson.",
    },
  ],
  fx: [
    { type: "ring", a: 3.3, b: 6.2, ...box(A, 90, 1950, 620, 135, 8) },
    { type: "ring", a: 6.4, b: 8.0, ...box(B, 90, 400, 950, 90, 8) },
    {
      type: "stamp",
      a: 6.5,
      b: 8.0,
      x: 760,
      y: 250,
      size: 80,
      text: "Raté",
      cls: "ink",
      r: 4,
    },
    { type: "ring", a: 8.1, b: 9.7, ...box(B, 90, 1100, 950, 240, 8) },
    {
      type: "stamp",
      a: 12.8,
      b: 14.2,
      x: 540,
      y: 1560,
      size: 130,
      text: "Trouvé ! 🎉",
      cls: "gr",
      r: -4,
    },
    { type: "confetti", a: 12.8, b: 14.2, x: 540, y: 1000 },
    { type: "ring", a: 14.6, b: 17.2, ...box(E, 90, 1490, 950, 380, 8) },
  ],
  outro: { a: 17.2, l1: "Une nouvelle chanson|*chaque jour*" },
};
